# Generated by Django 5.1.7 on 2025-03-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
